# Generated by Django 4.2.6 on 2023-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('population', models.IntegerField()),
                ('owner', models.IntegerField()),
            ],
        ),
    ]
